#!/bin/sh

if ! which podman > /dev/null 2>&1; then
	echo "podman is not in your path"
	exit 1
fi

CONTAINER_DIR="$(dirname "$(realpath "${0}")")"
CONTAINER_TAG="dbt3-appimage"
TARGET="appimage"

# Use the return code from `podman inspect` to determine if the container image
# needs to be created.
if ! podman inspect $CONTAINER_TAG > /dev/null 2>&1; then
	"${CONTAINER_DIR}/build-appimage-container" || exit 1
fi

if [ "$ARCH" = "" ]; then
	ARCH="x86_64"
fi

# Apply patches for successful builds on the old CentOS 7 container image
podman run \
		--rm \
		--user "$(id -u):$(id -u)" \
		--userns=keep-id \
		-v "${CONTAINER_DIR}/..:/usr/local/src/dbt3:rw,Z" \
		--env PKG_CONFIG_PATH="/usr/lib/pkgconfig" \
		--env ARCH="$ARCH" \
		--env DBGEN="${DBGEN}" \
		-w /usr/local/src/dbt3 \
		$CONTAINER_TAG \
		make VERBOSE=1 DBMS="${DBMS}" -f Makefile.cmake "${TARGET}"
