on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Upload Release Asset
jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build container
        run: |
          set -x
          sh -ex tools/build-appimage-container

      - name: build appimage
        run: |
          set -x
          ARCH=$(uname -m) sh -ex tools/build-appimage

      - name: create release
        run: |
          set -x
          assets=()
          for asset in $(find . -name '*.AppImage'); do
            assets+=("$asset")
            bname=$(basename "$asset")
            dname=$(dirname "$asset")
            (cd "$dname" && md5sum "$bname" > "${bname}.md5")
            (cd "$dname" && sha256sum "$bname" > "${bname}.sha256")
          done
          for asset in $(find . -name '*.md5'); do
            assets+=("$asset")
          done
          for asset in $(find . -name '*.sha256'); do
            assets+=("$asset")
          done
          tag="${GITHUB_REF##*/}"
          gh release create --repo="${GITHUB_REPOSITORY}" ${tag} ${assets[@]}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
